### ISSUE TITLE
About evaluation

### ISSUE THREAD

**Issue by ftgreat** [UbiquitousLearning/SLM_Survey#3]
Thanks a lot for your sharing. @Luzhenyan 
Did the paper evaluate all models, and what evaluation tools were used? 
Thank you.

**Comment by caidongqi** [comment]
We benchmark all the models shown in Figure 1, expect from the ones that are not open-sourced before the paper released.

We utilise [lm-evaluation-harness](https://doi.org/10.5281/zenodo.12608602) to evaluate the model accuracy.

Thank you for your attention to our work. I hope my answer can be helpful to you.

**Comment by ftgreat** [comment]
@caidongqi How to choose metric, acc or acc_norm, as follows. Thanks for your reply.

<img width="552" alt="image" src="https://github.com/user-attachments/assets/064e4b87-4936-47c3-a924-a5ac5e130dec">

**Comment by lx200916** [comment]
Hi,We use the metrics `acc,none` for all datasets, based on the following considerations:  
1. Not all datasets have `acc,norm` indicators. Using a consistent set of metrics is more friendly and fair to our sampling approach for averaging across multiple datasets.  
2. The calculation of `acc,norm` is related not only to `acc` but also to factors such as output length. We aim to simply evaluate the model's accuracy. (Although some tech reports select the higher value between `acc,none` and `acc,norm` to highlight their model's competitiveness, we do not need to do so.)
